// One-off build script: parses ../Capability/data.csv into data.js (embedded JS array)
// Run with: node build-data.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const csvPath = path.join(__dirname, '..', 'Capability', 'data.csv');
const outPath = path.join(__dirname, 'data.js');

let raw = fs.readFileSync(csvPath, 'utf8');
if (raw.charCodeAt(0) === 0xFEFF) raw = raw.slice(1); // strip BOM

function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    const next = text[i + 1];
    if (inQuotes) {
      if (c === '"' && next === '"') { field += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { field += c; }
    } else {
      if (c === '"') { inQuotes = true; }
      else if (c === ',') { row.push(field); field = ''; }
      else if (c === '\r') { /* skip */ }
      else if (c === '\n') { row.push(field); field = ''; rows.push(row); row = []; }
      else { field += c; }
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const rows = parseCSV(raw).filter(r => r.some(c => c && c.trim().length));
const header = rows[0].map(h => h.trim());
const dataRows = rows.slice(1);

const records = dataRows.map(r => {
  const rec = {};
  header.forEach((h, i) => { rec[h] = (r[i] || '').trim(); });
  return rec;
}).filter(r => r['Organization'] && r['Organization'].trim());

// Normalize keys to simpler names
const clean = records.map(r => ({
  ecosystem: r['Ecosystem'] || '',
  organization: r['Organization'] || '',
  cluster: r['Research Clusters/ Hubs'] || '',
  program: r['Labs/ Programs'] || '',
  description: (r['Lab/ Program Description'] || '').replace(/\s+/g, ' ').trim(),
  link: r['Link'] || ''
}));

const clusters = [...new Set(clean.map(r => r.cluster).filter(Boolean))].sort();

const out = `// AUTO-GENERATED by build-data.mjs from Capability/data.csv — do not hand-edit.
window.CAPABILITY_DATA = ${JSON.stringify(clean, null, 2)};
window.CAPABILITY_CLUSTERS = ${JSON.stringify(clusters, null, 2)};
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${clean.length} records, ${clusters.length} unique clusters to ${outPath}`);
console.log(clusters.join('\n'));
